{
  "swagger": "2.0",
  "info": {
    "title": "Webstack Chain - HTTP API Console",
    "description": "REST API for the Webstack chain custom modules",
    "version": "version not set"
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/webstack/licenses/admin_key/{address}": {
      "get": {
        "operationId": "Query_AdminKey",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/QueryAdminKeyResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "parameters": [
          {
            "name": "address",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "Query"
        ]
      }
    },
    "/webstack/licenses/admin_keys": {
      "get": {
        "operationId": "Query_AdminKeys",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/QueryAdminKeysResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "parameters": [
          {
            "name": "pagination.key",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "byte"
          },
          {
            "name": "pagination.offset",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.limit",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.count_total",
            "in": "query",
            "required": false,
            "type": "boolean"
          },
          {
            "name": "pagination.reverse",
            "in": "query",
            "required": false,
            "type": "boolean"
          }
        ],
        "tags": [
          "Query"
        ]
      }
    },
    "/webstack/licenses/admin_keys_by_license_type/{license_type_id}": {
      "get": {
        "operationId": "Query_AdminKeysByLicenseType",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/QueryAdminKeysByLicenseTypeResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "parameters": [
          {
            "name": "license_type_id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "permission",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "pagination.key",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "byte"
          },
          {
            "name": "pagination.offset",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.limit",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.count_total",
            "in": "query",
            "required": false,
            "type": "boolean"
          },
          {
            "name": "pagination.reverse",
            "in": "query",
            "required": false,
            "type": "boolean"
          }
        ],
        "tags": [
          "Query"
        ]
      }
    },
    "/webstack/licenses/license/{type_id}/{id}": {
      "get": {
        "operationId": "Query_License",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/QueryLicenseResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "parameters": [
          {
            "name": "type_id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "format": "uint64"
          }
        ],
        "tags": [
          "Query"
        ]
      }
    },
    "/webstack/licenses/license_type/{id}": {
      "get": {
        "operationId": "Query_LicenseType",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/QueryLicenseTypeResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "Query"
        ]
      }
    },
    "/webstack/licenses/license_types": {
      "get": {
        "operationId": "Query_LicenseTypes",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/QueryLicenseTypesResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "parameters": [
          {
            "name": "pagination.key",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "byte"
          },
          {
            "name": "pagination.offset",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.limit",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.count_total",
            "in": "query",
            "required": false,
            "type": "boolean"
          },
          {
            "name": "pagination.reverse",
            "in": "query",
            "required": false,
            "type": "boolean"
          }
        ],
        "tags": [
          "Query"
        ]
      }
    },
    "/webstack/licenses/licenses_by_holder/{holder}": {
      "get": {
        "operationId": "Query_LicensesByHolder",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/QueryLicensesByHolderResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "parameters": [
          {
            "name": "holder",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "pagination.key",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "byte"
          },
          {
            "name": "pagination.offset",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.limit",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.count_total",
            "in": "query",
            "required": false,
            "type": "boolean"
          },
          {
            "name": "pagination.reverse",
            "in": "query",
            "required": false,
            "type": "boolean"
          }
        ],
        "tags": [
          "Query"
        ]
      }
    },
    "/webstack/licenses/licenses_by_holder/{holder}/{type_id}": {
      "get": {
        "operationId": "Query_LicensesByHolderAndType",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/QueryLicensesByHolderAndTypeResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "parameters": [
          {
            "name": "holder",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "type_id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "pagination.key",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "byte"
          },
          {
            "name": "pagination.offset",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.limit",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.count_total",
            "in": "query",
            "required": false,
            "type": "boolean"
          },
          {
            "name": "pagination.reverse",
            "in": "query",
            "required": false,
            "type": "boolean"
          }
        ],
        "tags": [
          "Query"
        ]
      }
    },
    "/webstack/licenses/licenses_by_type/{type_id}": {
      "get": {
        "operationId": "Query_LicensesByType",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/QueryLicensesByTypeResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "parameters": [
          {
            "name": "type_id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "pagination.key",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "byte"
          },
          {
            "name": "pagination.offset",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.limit",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "uint64"
          },
          {
            "name": "pagination.count_total",
            "in": "query",
            "required": false,
            "type": "boolean"
          },
          {
            "name": "pagination.reverse",
            "in": "query",
            "required": false,
            "type": "boolean"
          }
        ],
        "tags": [
          "Query"
        ]
      }
    },
    "/webstack/licenses/params": {
      "get": {
        "operationId": "Query_Params",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/QueryParamsResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "tags": [
          "Query"
        ]
      }
    }
  },
  "definitions": {
    "Any": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "Status": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/Any"
          }
        }
      }
    },
    "AdminKeyGrant": {
      "type": "object",
      "properties": {
        "permission": {
          "type": "string"
        },
        "license_types": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "PageRequest": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string",
          "format": "byte"
        },
        "offset": {
          "type": "string",
          "format": "uint64"
        },
        "limit": {
          "type": "string",
          "format": "uint64"
        },
        "count_total": {
          "type": "boolean"
        },
        "reverse": {
          "type": "boolean"
        }
      }
    },
    "PageResponse": {
      "type": "object",
      "properties": {
        "next_key": {
          "type": "string",
          "format": "byte"
        },
        "total": {
          "type": "string",
          "format": "uint64"
        }
      }
    },
    "QueryAdminKeyResponse": {
      "type": "object",
      "properties": {
        "admin_key": {
          "$ref": "#/definitions/licenses.AdminKey"
        }
      }
    },
    "QueryAdminKeysByLicenseTypeResponse": {
      "type": "object",
      "properties": {
        "admin_keys": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/licenses.AdminKey"
          }
        },
        "pagination": {
          "$ref": "#/definitions/PageResponse"
        }
      }
    },
    "QueryAdminKeysResponse": {
      "type": "object",
      "properties": {
        "admin_keys": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/licenses.AdminKey"
          }
        },
        "pagination": {
          "$ref": "#/definitions/PageResponse"
        }
      }
    },
    "QueryLicenseResponse": {
      "type": "object",
      "properties": {
        "license": {
          "$ref": "#/definitions/licenses.License"
        }
      }
    },
    "QueryLicenseTypeResponse": {
      "type": "object",
      "properties": {
        "license_type": {
          "$ref": "#/definitions/licenses.LicenseType"
        }
      }
    },
    "QueryLicenseTypesResponse": {
      "type": "object",
      "properties": {
        "license_types": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/licenses.LicenseType"
          }
        },
        "pagination": {
          "$ref": "#/definitions/PageResponse"
        }
      }
    },
    "QueryLicensesByHolderAndTypeResponse": {
      "type": "object",
      "properties": {
        "licenses": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/licenses.License"
          }
        },
        "pagination": {
          "$ref": "#/definitions/PageResponse"
        }
      }
    },
    "QueryLicensesByHolderResponse": {
      "type": "object",
      "properties": {
        "licenses": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/licenses.License"
          }
        },
        "pagination": {
          "$ref": "#/definitions/PageResponse"
        }
      }
    },
    "QueryLicensesByTypeResponse": {
      "type": "object",
      "properties": {
        "licenses": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/licenses.License"
          }
        },
        "pagination": {
          "$ref": "#/definitions/PageResponse"
        }
      }
    },
    "QueryParamsResponse": {
      "type": "object",
      "properties": {
        "params": {
          "$ref": "#/definitions/licenses.Params"
        }
      }
    },
    "licenses.AdminKey": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string"
        },
        "grants": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/AdminKeyGrant"
          }
        }
      }
    },
    "licenses.License": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uint64"
        },
        "type": {
          "type": "string"
        },
        "holder": {
          "type": "string"
        },
        "start_date": {
          "type": "string"
        },
        "end_date": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "licenses.LicenseType": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "transferrable": {
          "type": "boolean"
        },
        "max_supply": {
          "type": "string"
        },
        "issued_count": {
          "type": "string"
        }
      }
    },
    "licenses.Params": {
      "type": "object",
      "properties": {
        "owner": {
          "type": "string"
        }
      }
    }
  }
}
