// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: license/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryLicenseTypeRequest is the request type for the Query/LicenseType RPC method.
type QueryLicenseTypeRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryLicenseTypeRequest) Reset()         { *m = QueryLicenseTypeRequest{} }
func (m *QueryLicenseTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLicenseTypeRequest) ProtoMessage()    {}
func (*QueryLicenseTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{0}
}
func (m *QueryLicenseTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicenseTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicenseTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicenseTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicenseTypeRequest.Merge(m, src)
}
func (m *QueryLicenseTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicenseTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicenseTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicenseTypeRequest proto.InternalMessageInfo

func (m *QueryLicenseTypeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryLicenseTypeResponse is the response type for the Query/LicenseType RPC method.
type QueryLicenseTypeResponse struct {
	LicenseType LicenseType `protobuf:"bytes,1,opt,name=license_type,json=licenseType,proto3" json:"license_type"`
}

func (m *QueryLicenseTypeResponse) Reset()         { *m = QueryLicenseTypeResponse{} }
func (m *QueryLicenseTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLicenseTypeResponse) ProtoMessage()    {}
func (*QueryLicenseTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{1}
}
func (m *QueryLicenseTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicenseTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicenseTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicenseTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicenseTypeResponse.Merge(m, src)
}
func (m *QueryLicenseTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicenseTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicenseTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicenseTypeResponse proto.InternalMessageInfo

func (m *QueryLicenseTypeResponse) GetLicenseType() LicenseType {
	if m != nil {
		return m.LicenseType
	}
	return LicenseType{}
}

// QueryLicenseTypesRequest is the request type for the Query/LicenseTypes RPC method.
type QueryLicenseTypesRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLicenseTypesRequest) Reset()         { *m = QueryLicenseTypesRequest{} }
func (m *QueryLicenseTypesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLicenseTypesRequest) ProtoMessage()    {}
func (*QueryLicenseTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{2}
}
func (m *QueryLicenseTypesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicenseTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicenseTypesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicenseTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicenseTypesRequest.Merge(m, src)
}
func (m *QueryLicenseTypesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicenseTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicenseTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicenseTypesRequest proto.InternalMessageInfo

func (m *QueryLicenseTypesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLicenseTypesResponse is the response type for the Query/LicenseTypes RPC method.
type QueryLicenseTypesResponse struct {
	LicenseTypes []LicenseType       `protobuf:"bytes,1,rep,name=license_types,json=licenseTypes,proto3" json:"license_types"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLicenseTypesResponse) Reset()         { *m = QueryLicenseTypesResponse{} }
func (m *QueryLicenseTypesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLicenseTypesResponse) ProtoMessage()    {}
func (*QueryLicenseTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{3}
}
func (m *QueryLicenseTypesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicenseTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicenseTypesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicenseTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicenseTypesResponse.Merge(m, src)
}
func (m *QueryLicenseTypesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicenseTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicenseTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicenseTypesResponse proto.InternalMessageInfo

func (m *QueryLicenseTypesResponse) GetLicenseTypes() []LicenseType {
	if m != nil {
		return m.LicenseTypes
	}
	return nil
}

func (m *QueryLicenseTypesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLicenseRequest is the request type for the Query/License RPC method.
type QueryLicenseRequest struct {
	TypeId string `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Id     uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryLicenseRequest) Reset()         { *m = QueryLicenseRequest{} }
func (m *QueryLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLicenseRequest) ProtoMessage()    {}
func (*QueryLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{4}
}
func (m *QueryLicenseRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicenseRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicenseRequest.Merge(m, src)
}
func (m *QueryLicenseRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicenseRequest proto.InternalMessageInfo

func (m *QueryLicenseRequest) GetTypeId() string {
	if m != nil {
		return m.TypeId
	}
	return ""
}

func (m *QueryLicenseRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryLicenseResponse is the response type for the Query/License RPC method.
type QueryLicenseResponse struct {
	License License `protobuf:"bytes,1,opt,name=license,proto3" json:"license"`
}

func (m *QueryLicenseResponse) Reset()         { *m = QueryLicenseResponse{} }
func (m *QueryLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLicenseResponse) ProtoMessage()    {}
func (*QueryLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{5}
}
func (m *QueryLicenseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicenseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicenseResponse.Merge(m, src)
}
func (m *QueryLicenseResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicenseResponse proto.InternalMessageInfo

func (m *QueryLicenseResponse) GetLicense() License {
	if m != nil {
		return m.License
	}
	return License{}
}

// QueryLicensesRequest is the request type for the Query/Licenses RPC method.
type QueryLicensesRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLicensesRequest) Reset()         { *m = QueryLicensesRequest{} }
func (m *QueryLicensesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLicensesRequest) ProtoMessage()    {}
func (*QueryLicensesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{6}
}
func (m *QueryLicensesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicensesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicensesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicensesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicensesRequest.Merge(m, src)
}
func (m *QueryLicensesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicensesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicensesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicensesRequest proto.InternalMessageInfo

func (m *QueryLicensesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLicensesResponse is the response type for the Query/Licenses RPC method.
type QueryLicensesResponse struct {
	Licenses   []License           `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLicensesResponse) Reset()         { *m = QueryLicensesResponse{} }
func (m *QueryLicensesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLicensesResponse) ProtoMessage()    {}
func (*QueryLicensesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{7}
}
func (m *QueryLicensesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicensesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicensesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicensesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicensesResponse.Merge(m, src)
}
func (m *QueryLicensesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicensesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicensesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicensesResponse proto.InternalMessageInfo

func (m *QueryLicensesResponse) GetLicenses() []License {
	if m != nil {
		return m.Licenses
	}
	return nil
}

func (m *QueryLicensesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLicensesByTypeRequest is the request type for the Query/LicensesByType RPC method.
type QueryLicensesByTypeRequest struct {
	TypeId     string             `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLicensesByTypeRequest) Reset()         { *m = QueryLicensesByTypeRequest{} }
func (m *QueryLicensesByTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLicensesByTypeRequest) ProtoMessage()    {}
func (*QueryLicensesByTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{8}
}
func (m *QueryLicensesByTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicensesByTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicensesByTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicensesByTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicensesByTypeRequest.Merge(m, src)
}
func (m *QueryLicensesByTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicensesByTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicensesByTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicensesByTypeRequest proto.InternalMessageInfo

func (m *QueryLicensesByTypeRequest) GetTypeId() string {
	if m != nil {
		return m.TypeId
	}
	return ""
}

func (m *QueryLicensesByTypeRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLicensesByTypeResponse is the response type for the Query/LicensesByType RPC method.
type QueryLicensesByTypeResponse struct {
	Licenses   []License           `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLicensesByTypeResponse) Reset()         { *m = QueryLicensesByTypeResponse{} }
func (m *QueryLicensesByTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLicensesByTypeResponse) ProtoMessage()    {}
func (*QueryLicensesByTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{9}
}
func (m *QueryLicensesByTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicensesByTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicensesByTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicensesByTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicensesByTypeResponse.Merge(m, src)
}
func (m *QueryLicensesByTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicensesByTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicensesByTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicensesByTypeResponse proto.InternalMessageInfo

func (m *QueryLicensesByTypeResponse) GetLicenses() []License {
	if m != nil {
		return m.Licenses
	}
	return nil
}

func (m *QueryLicensesByTypeResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLicensesByHolderRequest is the request type for the Query/LicensesByHolder RPC method.
type QueryLicensesByHolderRequest struct {
	Holder     string             `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLicensesByHolderRequest) Reset()         { *m = QueryLicensesByHolderRequest{} }
func (m *QueryLicensesByHolderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLicensesByHolderRequest) ProtoMessage()    {}
func (*QueryLicensesByHolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{10}
}
func (m *QueryLicensesByHolderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicensesByHolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicensesByHolderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicensesByHolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicensesByHolderRequest.Merge(m, src)
}
func (m *QueryLicensesByHolderRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicensesByHolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicensesByHolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicensesByHolderRequest proto.InternalMessageInfo

func (m *QueryLicensesByHolderRequest) GetHolder() string {
	if m != nil {
		return m.Holder
	}
	return ""
}

func (m *QueryLicensesByHolderRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLicensesByHolderResponse is the response type for the Query/LicensesByHolder RPC method.
type QueryLicensesByHolderResponse struct {
	Licenses   []License           `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLicensesByHolderResponse) Reset()         { *m = QueryLicensesByHolderResponse{} }
func (m *QueryLicensesByHolderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLicensesByHolderResponse) ProtoMessage()    {}
func (*QueryLicensesByHolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{11}
}
func (m *QueryLicensesByHolderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicensesByHolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicensesByHolderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicensesByHolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicensesByHolderResponse.Merge(m, src)
}
func (m *QueryLicensesByHolderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicensesByHolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicensesByHolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicensesByHolderResponse proto.InternalMessageInfo

func (m *QueryLicensesByHolderResponse) GetLicenses() []License {
	if m != nil {
		return m.Licenses
	}
	return nil
}

func (m *QueryLicensesByHolderResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLicensesByHolderAndTypeRequest is the request type for the Query/LicensesByHolderAndType RPC method.
type QueryLicensesByHolderAndTypeRequest struct {
	Holder     string             `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	TypeId     string             `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLicensesByHolderAndTypeRequest) Reset()         { *m = QueryLicensesByHolderAndTypeRequest{} }
func (m *QueryLicensesByHolderAndTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLicensesByHolderAndTypeRequest) ProtoMessage()    {}
func (*QueryLicensesByHolderAndTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{12}
}
func (m *QueryLicensesByHolderAndTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicensesByHolderAndTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicensesByHolderAndTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicensesByHolderAndTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicensesByHolderAndTypeRequest.Merge(m, src)
}
func (m *QueryLicensesByHolderAndTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicensesByHolderAndTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicensesByHolderAndTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicensesByHolderAndTypeRequest proto.InternalMessageInfo

func (m *QueryLicensesByHolderAndTypeRequest) GetHolder() string {
	if m != nil {
		return m.Holder
	}
	return ""
}

func (m *QueryLicensesByHolderAndTypeRequest) GetTypeId() string {
	if m != nil {
		return m.TypeId
	}
	return ""
}

func (m *QueryLicensesByHolderAndTypeRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLicensesByHolderAndTypeResponse is the response type for the Query/LicensesByHolderAndType RPC method.
type QueryLicensesByHolderAndTypeResponse struct {
	Licenses   []License           `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLicensesByHolderAndTypeResponse) Reset()         { *m = QueryLicensesByHolderAndTypeResponse{} }
func (m *QueryLicensesByHolderAndTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLicensesByHolderAndTypeResponse) ProtoMessage()    {}
func (*QueryLicensesByHolderAndTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123a6d691ebc3102, []int{13}
}
func (m *QueryLicensesByHolderAndTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLicensesByHolderAndTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLicensesByHolderAndTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLicensesByHolderAndTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLicensesByHolderAndTypeResponse.Merge(m, src)
}
func (m *QueryLicensesByHolderAndTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLicensesByHolderAndTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLicensesByHolderAndTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLicensesByHolderAndTypeResponse proto.InternalMessageInfo

func (m *QueryLicensesByHolderAndTypeResponse) GetLicenses() []License {
	if m != nil {
		return m.Licenses
	}
	return nil
}

func (m *QueryLicensesByHolderAndTypeResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryLicenseTypeRequest)(nil), "license.v1.QueryLicenseTypeRequest")
	proto.RegisterType((*QueryLicenseTypeResponse)(nil), "license.v1.QueryLicenseTypeResponse")
	proto.RegisterType((*QueryLicenseTypesRequest)(nil), "license.v1.QueryLicenseTypesRequest")
	proto.RegisterType((*QueryLicenseTypesResponse)(nil), "license.v1.QueryLicenseTypesResponse")
	proto.RegisterType((*QueryLicenseRequest)(nil), "license.v1.QueryLicenseRequest")
	proto.RegisterType((*QueryLicenseResponse)(nil), "license.v1.QueryLicenseResponse")
	proto.RegisterType((*QueryLicensesRequest)(nil), "license.v1.QueryLicensesRequest")
	proto.RegisterType((*QueryLicensesResponse)(nil), "license.v1.QueryLicensesResponse")
	proto.RegisterType((*QueryLicensesByTypeRequest)(nil), "license.v1.QueryLicensesByTypeRequest")
	proto.RegisterType((*QueryLicensesByTypeResponse)(nil), "license.v1.QueryLicensesByTypeResponse")
	proto.RegisterType((*QueryLicensesByHolderRequest)(nil), "license.v1.QueryLicensesByHolderRequest")
	proto.RegisterType((*QueryLicensesByHolderResponse)(nil), "license.v1.QueryLicensesByHolderResponse")
	proto.RegisterType((*QueryLicensesByHolderAndTypeRequest)(nil), "license.v1.QueryLicensesByHolderAndTypeRequest")
	proto.RegisterType((*QueryLicensesByHolderAndTypeResponse)(nil), "license.v1.QueryLicensesByHolderAndTypeResponse")
}

func init() { proto.RegisterFile("license/v1/query.proto", fileDescriptor_123a6d691ebc3102) }

var fileDescriptor_123a6d691ebc3102 = []byte{
	// 803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x96, 0xcf, 0x4f, 0x13, 0x4d,
	0x18, 0xc7, 0x3b, 0x85, 0x17, 0x78, 0x1f, 0x78, 0xc9, 0x9b, 0x81, 0xf7, 0x6d, 0x59, 0xa1, 0xc0,
	0xf2, 0x1b, 0x65, 0xa7, 0x05, 0x89, 0xf1, 0xa2, 0xd2, 0x03, 0xfe, 0x3c, 0x68, 0xf5, 0x64, 0x8c,
	0xcd, 0x6e, 0x77, 0xb3, 0x6c, 0x28, 0xbb, 0xa5, 0xb3, 0xa0, 0x0d, 0xa9, 0x07, 0xa3, 0x9e, 0x4d,
	0x3c, 0xe0, 0x45, 0xbd, 0x19, 0xff, 0x00, 0x0f, 0x5e, 0xbc, 0x73, 0x24, 0x7a, 0xf1, 0x64, 0x0c,
	0xf8, 0x87, 0x98, 0xce, 0xcc, 0xb6, 0xbb, 0xd0, 0xdd, 0x02, 0xe1, 0xc0, 0x09, 0x76, 0xe6, 0x99,
	0xe7, 0xfb, 0x79, 0xbe, 0xcf, 0xfc, 0x28, 0xfc, 0x5f, 0xb4, 0x0a, 0x86, 0x4d, 0x0d, 0xb2, 0x99,
	0x21, 0xeb, 0x1b, 0x46, 0xb9, 0xa2, 0x94, 0xca, 0x8e, 0xeb, 0x60, 0x10, 0xe3, 0xca, 0x66, 0x46,
	0x9a, 0x2d, 0x38, 0x74, 0xcd, 0xa1, 0x44, 0x53, 0xa9, 0xc1, 0x83, 0xc8, 0x66, 0x46, 0x33, 0x5c,
	0x35, 0x43, 0x4a, 0xaa, 0x69, 0xd9, 0xaa, 0x6b, 0x39, 0x36, 0x5f, 0x27, 0x0d, 0xf0, 0xd8, 0x3c,
	0xfb, 0x22, 0xfc, 0x43, 0x4c, 0xf5, 0x9b, 0x8e, 0xe9, 0xf0, 0xf1, 0xda, 0x7f, 0x62, 0x74, 0xd0,
	0x74, 0x1c, 0xb3, 0x68, 0x10, 0xb5, 0x64, 0x11, 0xd5, 0xb6, 0x1d, 0x97, 0x65, 0xf3, 0xd6, 0x24,
	0x7d, 0x78, 0x1e, 0x11, 0x9f, 0x19, 0x3a, 0x3c, 0x93, 0x77, 0x2b, 0x25, 0x31, 0x2d, 0xcf, 0x40,
	0xe2, 0x5e, 0x8d, 0xf4, 0x0e, 0x9f, 0x7a, 0x50, 0x29, 0x19, 0x39, 0x63, 0x7d, 0xc3, 0xa0, 0x2e,
	0xee, 0x85, 0xb8, 0xa5, 0x27, 0xd1, 0x08, 0x9a, 0xfe, 0x3b, 0x17, 0xb7, 0x74, 0xf9, 0x11, 0x24,
	0x0f, 0x87, 0xd2, 0x92, 0x63, 0x53, 0x03, 0x5f, 0x83, 0x1e, 0x7f, 0x72, 0xb6, 0xaa, 0x7b, 0x3e,
	0xa1, 0x34, 0xdc, 0x51, 0x7c, 0xcb, 0xb2, 0xed, 0x3b, 0x3f, 0x87, 0x63, 0xb9, 0xee, 0x62, 0x63,
	0x48, 0xd6, 0x0e, 0x67, 0xa7, 0x1e, 0xc9, 0x32, 0x40, 0xc3, 0x40, 0x91, 0x7b, 0x52, 0x11, 0xa6,
	0xd5, 0xdc, 0x56, 0x78, 0x4b, 0x84, 0xdb, 0xca, 0x5d, 0xd5, 0xf4, 0xaa, 0xc8, 0xf9, 0x56, 0xca,
	0x9f, 0x10, 0x0c, 0x34, 0x11, 0x11, 0x35, 0x64, 0xe1, 0x1f, 0x7f, 0x0d, 0x34, 0x89, 0x46, 0xda,
	0x5a, 0x17, 0xd1, 0xe3, 0x2b, 0x82, 0xe2, 0xeb, 0x01, 0xd2, 0x38, 0x23, 0x9d, 0x6a, 0x49, 0xca,
	0x01, 0x02, 0xa8, 0x57, 0xa0, 0xcf, 0x4f, 0xea, 0x39, 0x91, 0x80, 0xce, 0x1a, 0x5b, 0xbe, 0xde,
	0x98, 0x8e, 0xda, 0xe7, 0x4d, 0x5d, 0x34, 0xab, 0x26, 0xd8, 0xce, 0x9a, 0x75, 0x1b, 0xfa, 0x83,
	0xeb, 0x45, 0x91, 0x0b, 0xd0, 0x29, 0x80, 0x85, 0x8f, 0x7d, 0x4d, 0xca, 0x13, 0xa5, 0x79, 0x91,
	0xf2, 0xe3, 0x60, 0xb2, 0x53, 0xef, 0xcb, 0x36, 0x82, 0xff, 0x0e, 0x08, 0x08, 0xdc, 0x45, 0xe8,
	0x12, 0x10, 0x5e, 0x3b, 0x22, 0x78, 0xeb, 0xa1, 0xa7, 0xd7, 0x86, 0x2a, 0x48, 0x01, 0xb0, 0x6c,
	0xc5, 0x7f, 0x42, 0x42, 0xbb, 0xb1, 0xdc, 0x44, 0xff, 0x24, 0xc6, 0xbc, 0x43, 0x70, 0xae, 0xa9,
	0xfe, 0x19, 0xb1, 0xe7, 0x2d, 0x82, 0xc1, 0x03, 0x7c, 0x37, 0x9c, 0xa2, 0x6e, 0x94, 0x3d, 0x87,
	0xd2, 0xd0, 0xb1, 0xc2, 0x06, 0xb8, 0x41, 0xd9, 0xe4, 0xb7, 0xcf, 0x73, 0xfd, 0x42, 0x68, 0x49,
	0xd7, 0xcb, 0x06, 0xa5, 0xf7, 0xdd, 0xb2, 0x65, 0x9b, 0x39, 0x11, 0x77, 0x6a, 0xd6, 0x7d, 0x40,
	0x30, 0x14, 0x82, 0x76, 0x46, 0xcc, 0xfb, 0x82, 0x60, 0xac, 0x29, 0xe1, 0x92, 0xad, 0xfb, 0x77,
	0xd9, 0xf1, 0x3d, 0xf4, 0xed, 0xcb, 0x78, 0xc4, 0xbe, 0x6c, 0x3b, 0xb1, 0xb9, 0x1f, 0x11, 0x8c,
	0x47, 0xa3, 0x9f, 0x0d, 0x8f, 0xe7, 0x5f, 0x75, 0xc1, 0x5f, 0x0c, 0x14, 0xbf, 0x44, 0xd0, 0xed,
	0xbb, 0xbd, 0xf1, 0x98, 0x9f, 0x23, 0xe4, 0x09, 0x94, 0xc6, 0xa3, 0x83, 0xb8, 0xa0, 0x7c, 0xfe,
	0xf9, 0xf7, 0xdf, 0x6f, 0xe2, 0x13, 0x78, 0x8c, 0x3c, 0x31, 0x34, 0xea, 0xaa, 0x85, 0x55, 0xef,
	0xa5, 0x0d, 0xbc, 0xb8, 0x64, 0xcb, 0xd2, 0xab, 0xf8, 0x05, 0x82, 0x1e, 0xff, 0xf3, 0x83, 0x23,
	0x35, 0xbc, 0xab, 0x56, 0x9a, 0x68, 0x11, 0x25, 0x50, 0xa6, 0x18, 0xca, 0x28, 0x1e, 0x8e, 0x46,
	0xa1, 0xf8, 0x19, 0x74, 0x8a, 0x04, 0x78, 0x38, 0x2c, 0xb5, 0xa7, 0x3d, 0x12, 0x1e, 0x20, 0x64,
	0xd3, 0x4c, 0x76, 0x16, 0x4f, 0x87, 0xca, 0x92, 0x2d, 0xb1, 0x23, 0xab, 0xdc, 0x06, 0x0a, 0x5d,
	0xde, 0xde, 0xc1, 0xa1, 0xf9, 0xeb, 0xd5, 0x8f, 0x46, 0x44, 0x08, 0x04, 0x99, 0x21, 0x0c, 0x62,
	0x29, 0x14, 0x81, 0xe2, 0x6d, 0x04, 0xbd, 0xc1, 0x9b, 0x14, 0x4f, 0x86, 0x66, 0x0e, 0x5c, 0xf5,
	0xd2, 0x54, 0xcb, 0x38, 0xc1, 0x71, 0x91, 0x71, 0x28, 0xf8, 0x42, 0x38, 0x47, 0x5e, 0xab, 0x88,
	0x0d, 0xe1, 0x79, 0x82, 0xdf, 0x23, 0xf8, 0xf7, 0xe0, 0x59, 0xc2, 0xd3, 0x11, 0x9a, 0x81, 0x6b,
	0x56, 0x9a, 0x39, 0x42, 0xa4, 0xe0, 0x5b, 0x64, 0x7c, 0x04, 0xcf, 0x45, 0xf3, 0xf1, 0x9b, 0x84,
	0x6c, 0xf1, 0xbf, 0x55, 0xfc, 0x15, 0x41, 0x22, 0xe4, 0xb0, 0x63, 0xd2, 0x52, 0x3d, 0x78, 0xa3,
	0x49, 0xe9, 0xa3, 0x2f, 0x10, 0xd4, 0x57, 0x19, 0xf5, 0x65, 0x7c, 0xe9, 0x58, 0xd4, 0x0d, 0x83,
	0xb3, 0xb7, 0x76, 0xf6, 0x52, 0x68, 0x77, 0x2f, 0x85, 0x7e, 0xed, 0xa5, 0xd0, 0xeb, 0xfd, 0x54,
	0x6c, 0x77, 0x3f, 0x15, 0xfb, 0xb1, 0x9f, 0x8a, 0x3d, 0x4c, 0x9b, 0x96, 0xbb, 0xb2, 0xa1, 0x29,
	0x05, 0x67, 0xad, 0x9e, 0x7c, 0x8e, 0xea, 0xab, 0x0d, 0xa5, 0xa7, 0x75, 0x2d, 0x76, 0x76, 0xb4,
	0x0e, 0xf6, 0xd3, 0x79, 0xe1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x8d, 0xff, 0x07, 0x14,
	0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// LicenseType queries a license type by id.
	LicenseType(ctx context.Context, in *QueryLicenseTypeRequest, opts ...grpc.CallOption) (*QueryLicenseTypeResponse, error)
	// LicenseTypes queries all license types.
	LicenseTypes(ctx context.Context, in *QueryLicenseTypesRequest, opts ...grpc.CallOption) (*QueryLicenseTypesResponse, error)
	// License queries a license by type id and license id.
	License(ctx context.Context, in *QueryLicenseRequest, opts ...grpc.CallOption) (*QueryLicenseResponse, error)
	// Licenses queries all licenses across all license types, active and revoked.
	Licenses(ctx context.Context, in *QueryLicensesRequest, opts ...grpc.CallOption) (*QueryLicensesResponse, error)
	// LicensesByType queries all licenses for a given license type.
	LicensesByType(ctx context.Context, in *QueryLicensesByTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByTypeResponse, error)
	// LicensesByHolder queries the active licenses held by a given address.
	// Revoked licenses are not indexed by holder; use License or LicensesByType
	// to look them up.
	LicensesByHolder(ctx context.Context, in *QueryLicensesByHolderRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderResponse, error)
	// LicensesByHolderAndType queries the active licenses held by a given
	// address for a specific type. Revoked licenses are not indexed by holder;
	// use License or LicensesByType to look them up.
	LicensesByHolderAndType(ctx context.Context, in *QueryLicensesByHolderAndTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderAndTypeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) LicenseType(ctx context.Context, in *QueryLicenseTypeRequest, opts ...grpc.CallOption) (*QueryLicenseTypeResponse, error) {
	out := new(QueryLicenseTypeResponse)
	err := c.cc.Invoke(ctx, "/license.v1.Query/LicenseType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicenseTypes(ctx context.Context, in *QueryLicenseTypesRequest, opts ...grpc.CallOption) (*QueryLicenseTypesResponse, error) {
	out := new(QueryLicenseTypesResponse)
	err := c.cc.Invoke(ctx, "/license.v1.Query/LicenseTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) License(ctx context.Context, in *QueryLicenseRequest, opts ...grpc.CallOption) (*QueryLicenseResponse, error) {
	out := new(QueryLicenseResponse)
	err := c.cc.Invoke(ctx, "/license.v1.Query/License", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Licenses(ctx context.Context, in *QueryLicensesRequest, opts ...grpc.CallOption) (*QueryLicensesResponse, error) {
	out := new(QueryLicensesResponse)
	err := c.cc.Invoke(ctx, "/license.v1.Query/Licenses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicensesByType(ctx context.Context, in *QueryLicensesByTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByTypeResponse, error) {
	out := new(QueryLicensesByTypeResponse)
	err := c.cc.Invoke(ctx, "/license.v1.Query/LicensesByType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicensesByHolder(ctx context.Context, in *QueryLicensesByHolderRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderResponse, error) {
	out := new(QueryLicensesByHolderResponse)
	err := c.cc.Invoke(ctx, "/license.v1.Query/LicensesByHolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicensesByHolderAndType(ctx context.Context, in *QueryLicensesByHolderAndTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderAndTypeResponse, error) {
	out := new(QueryLicensesByHolderAndTypeResponse)
	err := c.cc.Invoke(ctx, "/license.v1.Query/LicensesByHolderAndType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// LicenseType queries a license type by id.
	LicenseType(context.Context, *QueryLicenseTypeRequest) (*QueryLicenseTypeResponse, error)
	// LicenseTypes queries all license types.
	LicenseTypes(context.Context, *QueryLicenseTypesRequest) (*QueryLicenseTypesResponse, error)
	// License queries a license by type id and license id.
	License(context.Context, *QueryLicenseRequest) (*QueryLicenseResponse, error)
	// Licenses queries all licenses across all license types, active and revoked.
	Licenses(context.Context, *QueryLicensesRequest) (*QueryLicensesResponse, error)
	// LicensesByType queries all licenses for a given license type.
	LicensesByType(context.Context, *QueryLicensesByTypeRequest) (*QueryLicensesByTypeResponse, error)
	// LicensesByHolder queries the active licenses held by a given address.
	// Revoked licenses are not indexed by holder; use License or LicensesByType
	// to look them up.
	LicensesByHolder(context.Context, *QueryLicensesByHolderRequest) (*QueryLicensesByHolderResponse, error)
	// LicensesByHolderAndType queries the active licenses held by a given
	// address for a specific type. Revoked licenses are not indexed by holder;
	// use License or LicensesByType to look them up.
	LicensesByHolderAndType(context.Context, *QueryLicensesByHolderAndTypeRequest) (*QueryLicensesByHolderAndTypeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) LicenseType(ctx context.Context, req *QueryLicenseTypeRequest) (*QueryLicenseTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicenseType not implemented")
}
func (*UnimplementedQueryServer) LicenseTypes(ctx context.Context, req *QueryLicenseTypesRequest) (*QueryLicenseTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicenseTypes not implemented")
}
func (*UnimplementedQueryServer) License(ctx context.Context, req *QueryLicenseRequest) (*QueryLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method License not implemented")
}
func (*UnimplementedQueryServer) Licenses(ctx context.Context, req *QueryLicensesRequest) (*QueryLicensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Licenses not implemented")
}
func (*UnimplementedQueryServer) LicensesByType(ctx context.Context, req *QueryLicensesByTypeRequest) (*QueryLicensesByTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicensesByType not implemented")
}
func (*UnimplementedQueryServer) LicensesByHolder(ctx context.Context, req *QueryLicensesByHolderRequest) (*QueryLicensesByHolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicensesByHolder not implemented")
}
func (*UnimplementedQueryServer) LicensesByHolderAndType(ctx context.Context, req *QueryLicensesByHolderAndTypeRequest) (*QueryLicensesByHolderAndTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicensesByHolderAndType not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_LicenseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicenseTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicenseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/license.v1.Query/LicenseType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicenseType(ctx, req.(*QueryLicenseTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicenseTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicenseTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicenseTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/license.v1.Query/LicenseTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicenseTypes(ctx, req.(*QueryLicenseTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_License_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).License(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/license.v1.Query/License",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).License(ctx, req.(*QueryLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Licenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Licenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/license.v1.Query/Licenses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Licenses(ctx, req.(*QueryLicensesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicensesByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicensesByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/license.v1.Query/LicensesByType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicensesByType(ctx, req.(*QueryLicensesByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicensesByHolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesByHolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicensesByHolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/license.v1.Query/LicensesByHolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicensesByHolder(ctx, req.(*QueryLicensesByHolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicensesByHolderAndType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesByHolderAndTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicensesByHolderAndType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/license.v1.Query/LicensesByHolderAndType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicensesByHolderAndType(ctx, req.(*QueryLicensesByHolderAndTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "license.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LicenseType",
			Handler:    _Query_LicenseType_Handler,
		},
		{
			MethodName: "LicenseTypes",
			Handler:    _Query_LicenseTypes_Handler,
		},
		{
			MethodName: "License",
			Handler:    _Query_License_Handler,
		},
		{
			MethodName: "Licenses",
			Handler:    _Query_Licenses_Handler,
		},
		{
			MethodName: "LicensesByType",
			Handler:    _Query_LicensesByType_Handler,
		},
		{
			MethodName: "LicensesByHolder",
			Handler:    _Query_LicensesByHolder_Handler,
		},
		{
			MethodName: "LicensesByHolderAndType",
			Handler:    _Query_LicensesByHolderAndType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "license/v1/query.proto",
}

func (m *QueryLicenseTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicenseTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicenseTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicenseTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicenseTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicenseTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LicenseType.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryLicenseTypesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicenseTypesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicenseTypesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicenseTypesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicenseTypesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicenseTypesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.LicenseTypes) > 0 {
		for iNdEx := len(m.LicenseTypes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LicenseTypes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicenseRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicenseRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicenseRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TypeId) > 0 {
		i -= len(m.TypeId)
		copy(dAtA[i:], m.TypeId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TypeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicenseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicenseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicenseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.License.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryLicensesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicensesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicensesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicensesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicensesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicensesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Licenses) > 0 {
		for iNdEx := len(m.Licenses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Licenses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicensesByTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicensesByTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicensesByTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.TypeId) > 0 {
		i -= len(m.TypeId)
		copy(dAtA[i:], m.TypeId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TypeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicensesByTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicensesByTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicensesByTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Licenses) > 0 {
		for iNdEx := len(m.Licenses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Licenses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicensesByHolderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicensesByHolderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicensesByHolderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Holder) > 0 {
		i -= len(m.Holder)
		copy(dAtA[i:], m.Holder)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Holder)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicensesByHolderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicensesByHolderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicensesByHolderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Licenses) > 0 {
		for iNdEx := len(m.Licenses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Licenses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicensesByHolderAndTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicensesByHolderAndTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicensesByHolderAndTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TypeId) > 0 {
		i -= len(m.TypeId)
		copy(dAtA[i:], m.TypeId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TypeId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Holder) > 0 {
		i -= len(m.Holder)
		copy(dAtA[i:], m.Holder)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Holder)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLicensesByHolderAndTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLicensesByHolderAndTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLicensesByHolderAndTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Licenses) > 0 {
		for iNdEx := len(m.Licenses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Licenses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryLicenseTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLicenseTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LicenseType.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLicenseTypesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLicenseTypesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LicenseTypes) > 0 {
		for _, e := range m.LicenseTypes {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLicenseRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TypeId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryLicenseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.License.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLicensesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLicensesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Licenses) > 0 {
		for _, e := range m.Licenses {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLicensesByTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TypeId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLicensesByTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Licenses) > 0 {
		for _, e := range m.Licenses {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLicensesByHolderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Holder)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLicensesByHolderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Licenses) > 0 {
		for _, e := range m.Licenses {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLicensesByHolderAndTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Holder)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.TypeId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLicensesByHolderAndTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Licenses) > 0 {
		for _, e := range m.Licenses {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryLicenseTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicenseTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicenseTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicenseTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicenseTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicenseTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LicenseType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LicenseType.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicenseTypesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicenseTypesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicenseTypesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicenseTypesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicenseTypesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicenseTypesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LicenseTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LicenseTypes = append(m.LicenseTypes, LicenseType{})
			if err := m.LicenseTypes[len(m.LicenseTypes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicenseRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicenseRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicenseRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TypeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicenseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicenseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicenseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field License", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.License.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicensesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicensesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicensesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicensesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicensesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicensesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Licenses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Licenses = append(m.Licenses, License{})
			if err := m.Licenses[len(m.Licenses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicensesByTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicensesByTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicensesByTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TypeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicensesByTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicensesByTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicensesByTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Licenses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Licenses = append(m.Licenses, License{})
			if err := m.Licenses[len(m.Licenses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicensesByHolderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicensesByHolderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicensesByHolderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Holder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Holder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicensesByHolderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicensesByHolderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicensesByHolderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Licenses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Licenses = append(m.Licenses, License{})
			if err := m.Licenses[len(m.Licenses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicensesByHolderAndTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicensesByHolderAndTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicensesByHolderAndTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Holder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Holder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TypeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLicensesByHolderAndTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLicensesByHolderAndTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLicensesByHolderAndTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Licenses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Licenses = append(m.Licenses, License{})
			if err := m.Licenses[len(m.Licenses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
