// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: licenses/v1/query.proto

package licensesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName                   = "/licenses.v1.Query/Params"
	Query_LicenseType_FullMethodName              = "/licenses.v1.Query/LicenseType"
	Query_LicenseTypes_FullMethodName             = "/licenses.v1.Query/LicenseTypes"
	Query_License_FullMethodName                  = "/licenses.v1.Query/License"
	Query_Licenses_FullMethodName                 = "/licenses.v1.Query/Licenses"
	Query_LicensesByType_FullMethodName           = "/licenses.v1.Query/LicensesByType"
	Query_LicensesByHolder_FullMethodName         = "/licenses.v1.Query/LicensesByHolder"
	Query_LicensesByHolderAndType_FullMethodName  = "/licenses.v1.Query/LicensesByHolderAndType"
	Query_PermissionsByAddress_FullMethodName     = "/licenses.v1.Query/PermissionsByAddress"
	Query_Permissions_FullMethodName              = "/licenses.v1.Query/Permissions"
	Query_PermissionsByLicenseType_FullMethodName = "/licenses.v1.Query/PermissionsByLicenseType"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// LicenseType queries a license type by id.
	LicenseType(ctx context.Context, in *QueryLicenseTypeRequest, opts ...grpc.CallOption) (*QueryLicenseTypeResponse, error)
	// LicenseTypes queries all license types.
	LicenseTypes(ctx context.Context, in *QueryLicenseTypesRequest, opts ...grpc.CallOption) (*QueryLicenseTypesResponse, error)
	// License queries a license by type id and license id.
	License(ctx context.Context, in *QueryLicenseRequest, opts ...grpc.CallOption) (*QueryLicenseResponse, error)
	// Licenses queries all licenses across all license types, active and revoked.
	Licenses(ctx context.Context, in *QueryLicensesRequest, opts ...grpc.CallOption) (*QueryLicensesResponse, error)
	// LicensesByType queries all licenses for a given license type.
	LicensesByType(ctx context.Context, in *QueryLicensesByTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByTypeResponse, error)
	// LicensesByHolder queries the active licenses held by a given address.
	// Revoked licenses are not indexed by holder; use License or LicensesByType
	// to look them up.
	LicensesByHolder(ctx context.Context, in *QueryLicensesByHolderRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderResponse, error)
	// LicensesByHolderAndType queries the active licenses held by a given
	// address for a specific type. Revoked licenses are not indexed by holder;
	// use License or LicensesByType to look them up.
	LicensesByHolderAndType(ctx context.Context, in *QueryLicensesByHolderAndTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderAndTypeResponse, error)
	// PermissionsByAddress queries the permission grants for a given address.
	PermissionsByAddress(ctx context.Context, in *QueryPermissionsByAddressRequest, opts ...grpc.CallOption) (*QueryPermissionsByAddressResponse, error)
	// Permissions queries the permission grants of every address.
	Permissions(ctx context.Context, in *QueryPermissionsRequest, opts ...grpc.CallOption) (*QueryPermissionsResponse, error)
	// PermissionsByLicenseType queries addresses that have grants for a given license type.
	PermissionsByLicenseType(ctx context.Context, in *QueryPermissionsByLicenseTypeRequest, opts ...grpc.CallOption) (*QueryPermissionsByLicenseTypeResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicenseType(ctx context.Context, in *QueryLicenseTypeRequest, opts ...grpc.CallOption) (*QueryLicenseTypeResponse, error) {
	out := new(QueryLicenseTypeResponse)
	err := c.cc.Invoke(ctx, Query_LicenseType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicenseTypes(ctx context.Context, in *QueryLicenseTypesRequest, opts ...grpc.CallOption) (*QueryLicenseTypesResponse, error) {
	out := new(QueryLicenseTypesResponse)
	err := c.cc.Invoke(ctx, Query_LicenseTypes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) License(ctx context.Context, in *QueryLicenseRequest, opts ...grpc.CallOption) (*QueryLicenseResponse, error) {
	out := new(QueryLicenseResponse)
	err := c.cc.Invoke(ctx, Query_License_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Licenses(ctx context.Context, in *QueryLicensesRequest, opts ...grpc.CallOption) (*QueryLicensesResponse, error) {
	out := new(QueryLicensesResponse)
	err := c.cc.Invoke(ctx, Query_Licenses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicensesByType(ctx context.Context, in *QueryLicensesByTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByTypeResponse, error) {
	out := new(QueryLicensesByTypeResponse)
	err := c.cc.Invoke(ctx, Query_LicensesByType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicensesByHolder(ctx context.Context, in *QueryLicensesByHolderRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderResponse, error) {
	out := new(QueryLicensesByHolderResponse)
	err := c.cc.Invoke(ctx, Query_LicensesByHolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicensesByHolderAndType(ctx context.Context, in *QueryLicensesByHolderAndTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderAndTypeResponse, error) {
	out := new(QueryLicensesByHolderAndTypeResponse)
	err := c.cc.Invoke(ctx, Query_LicensesByHolderAndType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PermissionsByAddress(ctx context.Context, in *QueryPermissionsByAddressRequest, opts ...grpc.CallOption) (*QueryPermissionsByAddressResponse, error) {
	out := new(QueryPermissionsByAddressResponse)
	err := c.cc.Invoke(ctx, Query_PermissionsByAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Permissions(ctx context.Context, in *QueryPermissionsRequest, opts ...grpc.CallOption) (*QueryPermissionsResponse, error) {
	out := new(QueryPermissionsResponse)
	err := c.cc.Invoke(ctx, Query_Permissions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PermissionsByLicenseType(ctx context.Context, in *QueryPermissionsByLicenseTypeRequest, opts ...grpc.CallOption) (*QueryPermissionsByLicenseTypeResponse, error) {
	out := new(QueryPermissionsByLicenseTypeResponse)
	err := c.cc.Invoke(ctx, Query_PermissionsByLicenseType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params queries the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// LicenseType queries a license type by id.
	LicenseType(context.Context, *QueryLicenseTypeRequest) (*QueryLicenseTypeResponse, error)
	// LicenseTypes queries all license types.
	LicenseTypes(context.Context, *QueryLicenseTypesRequest) (*QueryLicenseTypesResponse, error)
	// License queries a license by type id and license id.
	License(context.Context, *QueryLicenseRequest) (*QueryLicenseResponse, error)
	// Licenses queries all licenses across all license types, active and revoked.
	Licenses(context.Context, *QueryLicensesRequest) (*QueryLicensesResponse, error)
	// LicensesByType queries all licenses for a given license type.
	LicensesByType(context.Context, *QueryLicensesByTypeRequest) (*QueryLicensesByTypeResponse, error)
	// LicensesByHolder queries the active licenses held by a given address.
	// Revoked licenses are not indexed by holder; use License or LicensesByType
	// to look them up.
	LicensesByHolder(context.Context, *QueryLicensesByHolderRequest) (*QueryLicensesByHolderResponse, error)
	// LicensesByHolderAndType queries the active licenses held by a given
	// address for a specific type. Revoked licenses are not indexed by holder;
	// use License or LicensesByType to look them up.
	LicensesByHolderAndType(context.Context, *QueryLicensesByHolderAndTypeRequest) (*QueryLicensesByHolderAndTypeResponse, error)
	// PermissionsByAddress queries the permission grants for a given address.
	PermissionsByAddress(context.Context, *QueryPermissionsByAddressRequest) (*QueryPermissionsByAddressResponse, error)
	// Permissions queries the permission grants of every address.
	Permissions(context.Context, *QueryPermissionsRequest) (*QueryPermissionsResponse, error)
	// PermissionsByLicenseType queries addresses that have grants for a given license type.
	PermissionsByLicenseType(context.Context, *QueryPermissionsByLicenseTypeRequest) (*QueryPermissionsByLicenseTypeResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) LicenseType(context.Context, *QueryLicenseTypeRequest) (*QueryLicenseTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicenseType not implemented")
}
func (UnimplementedQueryServer) LicenseTypes(context.Context, *QueryLicenseTypesRequest) (*QueryLicenseTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicenseTypes not implemented")
}
func (UnimplementedQueryServer) License(context.Context, *QueryLicenseRequest) (*QueryLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method License not implemented")
}
func (UnimplementedQueryServer) Licenses(context.Context, *QueryLicensesRequest) (*QueryLicensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Licenses not implemented")
}
func (UnimplementedQueryServer) LicensesByType(context.Context, *QueryLicensesByTypeRequest) (*QueryLicensesByTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicensesByType not implemented")
}
func (UnimplementedQueryServer) LicensesByHolder(context.Context, *QueryLicensesByHolderRequest) (*QueryLicensesByHolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicensesByHolder not implemented")
}
func (UnimplementedQueryServer) LicensesByHolderAndType(context.Context, *QueryLicensesByHolderAndTypeRequest) (*QueryLicensesByHolderAndTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicensesByHolderAndType not implemented")
}
func (UnimplementedQueryServer) PermissionsByAddress(context.Context, *QueryPermissionsByAddressRequest) (*QueryPermissionsByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PermissionsByAddress not implemented")
}
func (UnimplementedQueryServer) Permissions(context.Context, *QueryPermissionsRequest) (*QueryPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Permissions not implemented")
}
func (UnimplementedQueryServer) PermissionsByLicenseType(context.Context, *QueryPermissionsByLicenseTypeRequest) (*QueryPermissionsByLicenseTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PermissionsByLicenseType not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicenseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicenseTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicenseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LicenseType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicenseType(ctx, req.(*QueryLicenseTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicenseTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicenseTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicenseTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LicenseTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicenseTypes(ctx, req.(*QueryLicenseTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_License_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).License(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_License_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).License(ctx, req.(*QueryLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Licenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Licenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Licenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Licenses(ctx, req.(*QueryLicensesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicensesByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicensesByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LicensesByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicensesByType(ctx, req.(*QueryLicensesByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicensesByHolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesByHolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicensesByHolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LicensesByHolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicensesByHolder(ctx, req.(*QueryLicensesByHolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicensesByHolderAndType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesByHolderAndTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicensesByHolderAndType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LicensesByHolderAndType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicensesByHolderAndType(ctx, req.(*QueryLicensesByHolderAndTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PermissionsByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPermissionsByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PermissionsByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PermissionsByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PermissionsByAddress(ctx, req.(*QueryPermissionsByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Permissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Permissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Permissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Permissions(ctx, req.(*QueryPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PermissionsByLicenseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPermissionsByLicenseTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PermissionsByLicenseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PermissionsByLicenseType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PermissionsByLicenseType(ctx, req.(*QueryPermissionsByLicenseTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenses.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "LicenseType",
			Handler:    _Query_LicenseType_Handler,
		},
		{
			MethodName: "LicenseTypes",
			Handler:    _Query_LicenseTypes_Handler,
		},
		{
			MethodName: "License",
			Handler:    _Query_License_Handler,
		},
		{
			MethodName: "Licenses",
			Handler:    _Query_Licenses_Handler,
		},
		{
			MethodName: "LicensesByType",
			Handler:    _Query_LicensesByType_Handler,
		},
		{
			MethodName: "LicensesByHolder",
			Handler:    _Query_LicensesByHolder_Handler,
		},
		{
			MethodName: "LicensesByHolderAndType",
			Handler:    _Query_LicensesByHolderAndType_Handler,
		},
		{
			MethodName: "PermissionsByAddress",
			Handler:    _Query_PermissionsByAddress_Handler,
		},
		{
			MethodName: "Permissions",
			Handler:    _Query_Permissions_Handler,
		},
		{
			MethodName: "PermissionsByLicenseType",
			Handler:    _Query_PermissionsByLicenseType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "licenses/v1/query.proto",
}
