// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: licenses/v1/tx.proto

package licensesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName      = "/licenses.v1.Msg/UpdateParams"
	Msg_CreateLicenseType_FullMethodName = "/licenses.v1.Msg/CreateLicenseType"
	Msg_SetAdminKey_FullMethodName       = "/licenses.v1.Msg/SetAdminKey"
	Msg_RemoveAdminKey_FullMethodName    = "/licenses.v1.Msg/RemoveAdminKey"
	Msg_IssueLicense_FullMethodName      = "/licenses.v1.Msg/IssueLicense"
	Msg_RevokeLicense_FullMethodName     = "/licenses.v1.Msg/RevokeLicense"
	Msg_UpdateLicense_FullMethodName     = "/licenses.v1.Msg/UpdateLicense"
	Msg_TransferLicense_FullMethodName   = "/licenses.v1.Msg/TransferLicense"
	Msg_UpdateLicenseType_FullMethodName = "/licenses.v1.Msg/UpdateLicenseType"
	Msg_BatchIssueLicense_FullMethodName = "/licenses.v1.Msg/BatchIssueLicense"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a governance operation for updating the module parameters.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// CreateLicenseType creates a new license type. Signer must be the module owner.
	CreateLicenseType(ctx context.Context, in *MsgCreateLicenseType, opts ...grpc.CallOption) (*MsgCreateLicenseTypeResponse, error)
	// SetAdminKey adds or updates admin key grants for an address. Signer must be the module owner.
	SetAdminKey(ctx context.Context, in *MsgSetAdminKey, opts ...grpc.CallOption) (*MsgSetAdminKeyResponse, error)
	// RemoveAdminKey removes all admin key grants for an address. Signer must be the module owner.
	RemoveAdminKey(ctx context.Context, in *MsgRemoveAdminKey, opts ...grpc.CallOption) (*MsgRemoveAdminKeyResponse, error)
	// IssueLicense issues a new license. Signer must have the "issue" grant for the license type.
	IssueLicense(ctx context.Context, in *MsgIssueLicense, opts ...grpc.CallOption) (*MsgIssueLicenseResponse, error)
	// RevokeLicense deletes a license. Signer must have the "revoke" grant for the license type.
	RevokeLicense(ctx context.Context, in *MsgRevokeLicense, opts ...grpc.CallOption) (*MsgRevokeLicenseResponse, error)
	// UpdateLicense updates the status of a license. Signer must have the "update" grant for the license type.
	UpdateLicense(ctx context.Context, in *MsgUpdateLicense, opts ...grpc.CallOption) (*MsgUpdateLicenseResponse, error)
	// TransferLicense transfers a license to a new holder. Signer must be the current holder and the type must be transferrable.
	TransferLicense(ctx context.Context, in *MsgTransferLicense, opts ...grpc.CallOption) (*MsgTransferLicenseResponse, error)
	// UpdateLicenseType updates an existing license type. Signer must be the module owner.
	UpdateLicenseType(ctx context.Context, in *MsgUpdateLicenseType, opts ...grpc.CallOption) (*MsgUpdateLicenseTypeResponse, error)
	// BatchIssueLicense issues multiple licenses in a single transaction. Signer must have the "issue" grant for the license type.
	BatchIssueLicense(ctx context.Context, in *MsgBatchIssueLicense, opts ...grpc.CallOption) (*MsgBatchIssueLicenseResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateLicenseType(ctx context.Context, in *MsgCreateLicenseType, opts ...grpc.CallOption) (*MsgCreateLicenseTypeResponse, error) {
	out := new(MsgCreateLicenseTypeResponse)
	err := c.cc.Invoke(ctx, Msg_CreateLicenseType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetAdminKey(ctx context.Context, in *MsgSetAdminKey, opts ...grpc.CallOption) (*MsgSetAdminKeyResponse, error) {
	out := new(MsgSetAdminKeyResponse)
	err := c.cc.Invoke(ctx, Msg_SetAdminKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveAdminKey(ctx context.Context, in *MsgRemoveAdminKey, opts ...grpc.CallOption) (*MsgRemoveAdminKeyResponse, error) {
	out := new(MsgRemoveAdminKeyResponse)
	err := c.cc.Invoke(ctx, Msg_RemoveAdminKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) IssueLicense(ctx context.Context, in *MsgIssueLicense, opts ...grpc.CallOption) (*MsgIssueLicenseResponse, error) {
	out := new(MsgIssueLicenseResponse)
	err := c.cc.Invoke(ctx, Msg_IssueLicense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeLicense(ctx context.Context, in *MsgRevokeLicense, opts ...grpc.CallOption) (*MsgRevokeLicenseResponse, error) {
	out := new(MsgRevokeLicenseResponse)
	err := c.cc.Invoke(ctx, Msg_RevokeLicense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateLicense(ctx context.Context, in *MsgUpdateLicense, opts ...grpc.CallOption) (*MsgUpdateLicenseResponse, error) {
	out := new(MsgUpdateLicenseResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateLicense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferLicense(ctx context.Context, in *MsgTransferLicense, opts ...grpc.CallOption) (*MsgTransferLicenseResponse, error) {
	out := new(MsgTransferLicenseResponse)
	err := c.cc.Invoke(ctx, Msg_TransferLicense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateLicenseType(ctx context.Context, in *MsgUpdateLicenseType, opts ...grpc.CallOption) (*MsgUpdateLicenseTypeResponse, error) {
	out := new(MsgUpdateLicenseTypeResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateLicenseType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BatchIssueLicense(ctx context.Context, in *MsgBatchIssueLicense, opts ...grpc.CallOption) (*MsgBatchIssueLicenseResponse, error) {
	out := new(MsgBatchIssueLicenseResponse)
	err := c.cc.Invoke(ctx, Msg_BatchIssueLicense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a governance operation for updating the module parameters.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// CreateLicenseType creates a new license type. Signer must be the module owner.
	CreateLicenseType(context.Context, *MsgCreateLicenseType) (*MsgCreateLicenseTypeResponse, error)
	// SetAdminKey adds or updates admin key grants for an address. Signer must be the module owner.
	SetAdminKey(context.Context, *MsgSetAdminKey) (*MsgSetAdminKeyResponse, error)
	// RemoveAdminKey removes all admin key grants for an address. Signer must be the module owner.
	RemoveAdminKey(context.Context, *MsgRemoveAdminKey) (*MsgRemoveAdminKeyResponse, error)
	// IssueLicense issues a new license. Signer must have the "issue" grant for the license type.
	IssueLicense(context.Context, *MsgIssueLicense) (*MsgIssueLicenseResponse, error)
	// RevokeLicense deletes a license. Signer must have the "revoke" grant for the license type.
	RevokeLicense(context.Context, *MsgRevokeLicense) (*MsgRevokeLicenseResponse, error)
	// UpdateLicense updates the status of a license. Signer must have the "update" grant for the license type.
	UpdateLicense(context.Context, *MsgUpdateLicense) (*MsgUpdateLicenseResponse, error)
	// TransferLicense transfers a license to a new holder. Signer must be the current holder and the type must be transferrable.
	TransferLicense(context.Context, *MsgTransferLicense) (*MsgTransferLicenseResponse, error)
	// UpdateLicenseType updates an existing license type. Signer must be the module owner.
	UpdateLicenseType(context.Context, *MsgUpdateLicenseType) (*MsgUpdateLicenseTypeResponse, error)
	// BatchIssueLicense issues multiple licenses in a single transaction. Signer must have the "issue" grant for the license type.
	BatchIssueLicense(context.Context, *MsgBatchIssueLicense) (*MsgBatchIssueLicenseResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateLicenseType(context.Context, *MsgCreateLicenseType) (*MsgCreateLicenseTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLicenseType not implemented")
}
func (UnimplementedMsgServer) SetAdminKey(context.Context, *MsgSetAdminKey) (*MsgSetAdminKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAdminKey not implemented")
}
func (UnimplementedMsgServer) RemoveAdminKey(context.Context, *MsgRemoveAdminKey) (*MsgRemoveAdminKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAdminKey not implemented")
}
func (UnimplementedMsgServer) IssueLicense(context.Context, *MsgIssueLicense) (*MsgIssueLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueLicense not implemented")
}
func (UnimplementedMsgServer) RevokeLicense(context.Context, *MsgRevokeLicense) (*MsgRevokeLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeLicense not implemented")
}
func (UnimplementedMsgServer) UpdateLicense(context.Context, *MsgUpdateLicense) (*MsgUpdateLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLicense not implemented")
}
func (UnimplementedMsgServer) TransferLicense(context.Context, *MsgTransferLicense) (*MsgTransferLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferLicense not implemented")
}
func (UnimplementedMsgServer) UpdateLicenseType(context.Context, *MsgUpdateLicenseType) (*MsgUpdateLicenseTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLicenseType not implemented")
}
func (UnimplementedMsgServer) BatchIssueLicense(context.Context, *MsgBatchIssueLicense) (*MsgBatchIssueLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchIssueLicense not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateLicenseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLicenseType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateLicenseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateLicenseType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateLicenseType(ctx, req.(*MsgCreateLicenseType))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetAdminKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetAdminKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetAdminKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetAdminKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetAdminKey(ctx, req.(*MsgSetAdminKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveAdminKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveAdminKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveAdminKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RemoveAdminKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveAdminKey(ctx, req.(*MsgRemoveAdminKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_IssueLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgIssueLicense)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IssueLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_IssueLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IssueLicense(ctx, req.(*MsgIssueLicense))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeLicense)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevokeLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeLicense(ctx, req.(*MsgRevokeLicense))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateLicense)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateLicense(ctx, req.(*MsgUpdateLicense))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferLicense)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_TransferLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferLicense(ctx, req.(*MsgTransferLicense))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateLicenseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateLicenseType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateLicenseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateLicenseType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateLicenseType(ctx, req.(*MsgUpdateLicenseType))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BatchIssueLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBatchIssueLicense)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BatchIssueLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_BatchIssueLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BatchIssueLicense(ctx, req.(*MsgBatchIssueLicense))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenses.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateLicenseType",
			Handler:    _Msg_CreateLicenseType_Handler,
		},
		{
			MethodName: "SetAdminKey",
			Handler:    _Msg_SetAdminKey_Handler,
		},
		{
			MethodName: "RemoveAdminKey",
			Handler:    _Msg_RemoveAdminKey_Handler,
		},
		{
			MethodName: "IssueLicense",
			Handler:    _Msg_IssueLicense_Handler,
		},
		{
			MethodName: "RevokeLicense",
			Handler:    _Msg_RevokeLicense_Handler,
		},
		{
			MethodName: "UpdateLicense",
			Handler:    _Msg_UpdateLicense_Handler,
		},
		{
			MethodName: "TransferLicense",
			Handler:    _Msg_TransferLicense_Handler,
		},
		{
			MethodName: "UpdateLicenseType",
			Handler:    _Msg_UpdateLicenseType_Handler,
		},
		{
			MethodName: "BatchIssueLicense",
			Handler:    _Msg_BatchIssueLicense_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "licenses/v1/tx.proto",
}
