// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: licenses/v1/tx.proto

package licensesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName              = "/licenses.v1.Msg/UpdateParams"
	Msg_CreateLicenseType_FullMethodName         = "/licenses.v1.Msg/CreateLicenseType"
	Msg_GrantAdminPermissions_FullMethodName     = "/licenses.v1.Msg/GrantAdminPermissions"
	Msg_RevokeAdminKeyPermissions_FullMethodName = "/licenses.v1.Msg/RevokeAdminKeyPermissions"
	Msg_IssueLicenses_FullMethodName             = "/licenses.v1.Msg/IssueLicenses"
	Msg_RevokeLicenses_FullMethodName            = "/licenses.v1.Msg/RevokeLicenses"
	Msg_TransferLicense_FullMethodName           = "/licenses.v1.Msg/TransferLicense"
	Msg_UpdateLicenseType_FullMethodName         = "/licenses.v1.Msg/UpdateLicenseType"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a governance operation for updating the module parameters.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// CreateLicenseType creates a new license type. Signer must be the module owner.
	CreateLicenseType(ctx context.Context, in *MsgCreateLicenseType, opts ...grpc.CallOption) (*MsgCreateLicenseTypeResponse, error)
	// GrantAdminPermissions merges admin key grants for an address. Signer must be the module owner.
	// Existing grants for the address are preserved; new (permission, license type) pairs are unioned in.
	GrantAdminPermissions(ctx context.Context, in *MsgGrantAdminPermissions, opts ...grpc.CallOption) (*MsgGrantAdminPermissionsResponse, error)
	// RevokeAdminKeyPermissions removes the given (license type, permission) pairs from an admin
	// key's grants. If a grant's license types become empty it is dropped; if all grants are gone
	// the admin key entry itself is deleted. Signer must be the module owner.
	RevokeAdminKeyPermissions(ctx context.Context, in *MsgRevokeAdminKeyPermissions, opts ...grpc.CallOption) (*MsgRevokeAdminKeyPermissionsResponse, error)
	// IssueLicenses issues one or more licenses. Signer must have the "issue" grant for the license type.
	IssueLicenses(ctx context.Context, in *MsgIssueLicenses, opts ...grpc.CallOption) (*MsgIssueLicensesResponse, error)
	// RevokeLicenses revokes licenses for a holder, revoking the most recently issued first.
	// Signer must have the "revoke" grant for the license type.
	RevokeLicenses(ctx context.Context, in *MsgRevokeLicenses, opts ...grpc.CallOption) (*MsgRevokeLicensesResponse, error)
	// TransferLicense transfers a license to a new holder. Signer must be the current holder and the type must be transferrable.
	TransferLicense(ctx context.Context, in *MsgTransferLicense, opts ...grpc.CallOption) (*MsgTransferLicenseResponse, error)
	// UpdateLicenseType updates an existing license type. Signer must be the module owner.
	UpdateLicenseType(ctx context.Context, in *MsgUpdateLicenseType, opts ...grpc.CallOption) (*MsgUpdateLicenseTypeResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateLicenseType(ctx context.Context, in *MsgCreateLicenseType, opts ...grpc.CallOption) (*MsgCreateLicenseTypeResponse, error) {
	out := new(MsgCreateLicenseTypeResponse)
	err := c.cc.Invoke(ctx, Msg_CreateLicenseType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GrantAdminPermissions(ctx context.Context, in *MsgGrantAdminPermissions, opts ...grpc.CallOption) (*MsgGrantAdminPermissionsResponse, error) {
	out := new(MsgGrantAdminPermissionsResponse)
	err := c.cc.Invoke(ctx, Msg_GrantAdminPermissions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeAdminKeyPermissions(ctx context.Context, in *MsgRevokeAdminKeyPermissions, opts ...grpc.CallOption) (*MsgRevokeAdminKeyPermissionsResponse, error) {
	out := new(MsgRevokeAdminKeyPermissionsResponse)
	err := c.cc.Invoke(ctx, Msg_RevokeAdminKeyPermissions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) IssueLicenses(ctx context.Context, in *MsgIssueLicenses, opts ...grpc.CallOption) (*MsgIssueLicensesResponse, error) {
	out := new(MsgIssueLicensesResponse)
	err := c.cc.Invoke(ctx, Msg_IssueLicenses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeLicenses(ctx context.Context, in *MsgRevokeLicenses, opts ...grpc.CallOption) (*MsgRevokeLicensesResponse, error) {
	out := new(MsgRevokeLicensesResponse)
	err := c.cc.Invoke(ctx, Msg_RevokeLicenses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferLicense(ctx context.Context, in *MsgTransferLicense, opts ...grpc.CallOption) (*MsgTransferLicenseResponse, error) {
	out := new(MsgTransferLicenseResponse)
	err := c.cc.Invoke(ctx, Msg_TransferLicense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateLicenseType(ctx context.Context, in *MsgUpdateLicenseType, opts ...grpc.CallOption) (*MsgUpdateLicenseTypeResponse, error) {
	out := new(MsgUpdateLicenseTypeResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateLicenseType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a governance operation for updating the module parameters.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// CreateLicenseType creates a new license type. Signer must be the module owner.
	CreateLicenseType(context.Context, *MsgCreateLicenseType) (*MsgCreateLicenseTypeResponse, error)
	// GrantAdminPermissions merges admin key grants for an address. Signer must be the module owner.
	// Existing grants for the address are preserved; new (permission, license type) pairs are unioned in.
	GrantAdminPermissions(context.Context, *MsgGrantAdminPermissions) (*MsgGrantAdminPermissionsResponse, error)
	// RevokeAdminKeyPermissions removes the given (license type, permission) pairs from an admin
	// key's grants. If a grant's license types become empty it is dropped; if all grants are gone
	// the admin key entry itself is deleted. Signer must be the module owner.
	RevokeAdminKeyPermissions(context.Context, *MsgRevokeAdminKeyPermissions) (*MsgRevokeAdminKeyPermissionsResponse, error)
	// IssueLicenses issues one or more licenses. Signer must have the "issue" grant for the license type.
	IssueLicenses(context.Context, *MsgIssueLicenses) (*MsgIssueLicensesResponse, error)
	// RevokeLicenses revokes licenses for a holder, revoking the most recently issued first.
	// Signer must have the "revoke" grant for the license type.
	RevokeLicenses(context.Context, *MsgRevokeLicenses) (*MsgRevokeLicensesResponse, error)
	// TransferLicense transfers a license to a new holder. Signer must be the current holder and the type must be transferrable.
	TransferLicense(context.Context, *MsgTransferLicense) (*MsgTransferLicenseResponse, error)
	// UpdateLicenseType updates an existing license type. Signer must be the module owner.
	UpdateLicenseType(context.Context, *MsgUpdateLicenseType) (*MsgUpdateLicenseTypeResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateLicenseType(context.Context, *MsgCreateLicenseType) (*MsgCreateLicenseTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLicenseType not implemented")
}
func (UnimplementedMsgServer) GrantAdminPermissions(context.Context, *MsgGrantAdminPermissions) (*MsgGrantAdminPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantAdminPermissions not implemented")
}
func (UnimplementedMsgServer) RevokeAdminKeyPermissions(context.Context, *MsgRevokeAdminKeyPermissions) (*MsgRevokeAdminKeyPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeAdminKeyPermissions not implemented")
}
func (UnimplementedMsgServer) IssueLicenses(context.Context, *MsgIssueLicenses) (*MsgIssueLicensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueLicenses not implemented")
}
func (UnimplementedMsgServer) RevokeLicenses(context.Context, *MsgRevokeLicenses) (*MsgRevokeLicensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeLicenses not implemented")
}
func (UnimplementedMsgServer) TransferLicense(context.Context, *MsgTransferLicense) (*MsgTransferLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferLicense not implemented")
}
func (UnimplementedMsgServer) UpdateLicenseType(context.Context, *MsgUpdateLicenseType) (*MsgUpdateLicenseTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLicenseType not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateLicenseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLicenseType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateLicenseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateLicenseType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateLicenseType(ctx, req.(*MsgCreateLicenseType))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GrantAdminPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGrantAdminPermissions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GrantAdminPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_GrantAdminPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GrantAdminPermissions(ctx, req.(*MsgGrantAdminPermissions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeAdminKeyPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeAdminKeyPermissions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeAdminKeyPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevokeAdminKeyPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeAdminKeyPermissions(ctx, req.(*MsgRevokeAdminKeyPermissions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_IssueLicenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgIssueLicenses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IssueLicenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_IssueLicenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IssueLicenses(ctx, req.(*MsgIssueLicenses))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeLicenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeLicenses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeLicenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevokeLicenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeLicenses(ctx, req.(*MsgRevokeLicenses))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferLicense)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_TransferLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferLicense(ctx, req.(*MsgTransferLicense))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateLicenseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateLicenseType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateLicenseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateLicenseType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateLicenseType(ctx, req.(*MsgUpdateLicenseType))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenses.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateLicenseType",
			Handler:    _Msg_CreateLicenseType_Handler,
		},
		{
			MethodName: "GrantAdminPermissions",
			Handler:    _Msg_GrantAdminPermissions_Handler,
		},
		{
			MethodName: "RevokeAdminKeyPermissions",
			Handler:    _Msg_RevokeAdminKeyPermissions_Handler,
		},
		{
			MethodName: "IssueLicenses",
			Handler:    _Msg_IssueLicenses_Handler,
		},
		{
			MethodName: "RevokeLicenses",
			Handler:    _Msg_RevokeLicenses_Handler,
		},
		{
			MethodName: "TransferLicense",
			Handler:    _Msg_TransferLicense_Handler,
		},
		{
			MethodName: "UpdateLicenseType",
			Handler:    _Msg_UpdateLicenseType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "licenses/v1/tx.proto",
}
